### ISSUE TITLE
The game "Dog"

### ISSUE THREAD

**Issue by holu31** [0Nera/SynapseApps#1]
The game "Dog" does not support the synapse API, because it was created for windows.
I tried to collect it, but only the exe comes out, and if you collect through "i686-elf-gcc -nostdlib -lgcc -ffreestanding -I apps/include -c games/alesson/dog/dog.c -o dog.o", it does not come out. Please, fix or delete this game

**Comment by 0Nera** [comment]
Hello! The port of the game "dog" is not yet complete. The author of the program (Alesson) has not yet completely rewritten it. We apologize for the inconvenience caused.
